name: .Terraform Deployer

on:
  workflow_call:
    inputs:
      ### Required
      environment_name:
        description: 'The name of the environment to deploy to'
        required: true
        default: 'dev'
        type: string
      command:
        description: 'The terragrunt command to run'
        required: true
        default: 'apply'
        type: string
        

    
      
env:
    TG_VERSION: 0.55.2
    TF_VERSION: 1.5.3
    TG_SRC_PATH: terraform/backend
    AWS_REGION: ca-central-1
jobs:
 deploy_database:
  runs-on: ubuntu-24.04
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: ${{ inputs.environment_name }}-deployment
          aws-region: ${{ env.AWS_REGION }}
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v3
      with:
          terragrunt-version: ${{ env.TG_VERSION }}
    - name: Print Terraform directory
      working-directory: terraform/backend/${{ inputs.environment_name }}
      run: |
        ls -la
    - name: Terragrunt Apply
      working-directory: terraform/backend/${{ inputs.environment_name }}
      env:
          target_env: ${{ inputs.environment_name }}
          aws_license_plate: ${{ secrets.AWS_LICENSE_PLATE }}
      run: |
          # Run terraform
          terragrunt run-all ${{inputs.command}} --terragrunt-non-interactive