name: .Tests

on:
 workflow_call: 

jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Docker compose
        run: docker compose up -d --wait
        continue-on-error: true
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Tests
        env:
          E2E_BASE_URL: http://localhost:3000
          CI: 'true'
        run: |
          npx playwright test --project="chromium" --reporter=blob