name: .Tests

on:
 workflow_call: 
  inputs: 
    tag: 
      description: 'The tag of the containers to run tests on'
      required: true
      type: string

permissions:
  contents: write # This is required for actions/checkout
jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Docker compose
        env:
          BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend:${{ inputs.tag }}
          FLYWAY_IMAGE: ghcr.io/${{ github.repository }}/migrations:${{ inputs.tag }}
          FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/frontend:${{ inputs.tag }}
          FRONTEND_ENTRYPOINT: ' '
          BACKEND_ENTRYPOINT: ' '
        run: docker compose up -d --wait
        continue-on-error: true

      - name: Run Tests
        working-directory: frontend
        env:
          E2E_BASE_URL: http://localhost:3000
          CI: 'true'
        run: |
          npx playwright test --project="chromium" --reporter=blob