name: Merge

on:
  push:
    branches: [main]
  workflow_dispatch:
      inputs:
        pr_no:
            description: "PR-numbered container set to deploy"
            type: number
            required: true
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
env:
    AWS_REGION: ca-central-1
jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr || github.event.inputs.pr_no }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        if: ${{ github.event_name != 'workflow_dispatch' }} 
        id: pr
        uses: bcgov-nr/action-get-pr@21f9351425cd55a98e869ee28919a512aa30647d # v0.0.1
  
  deploy_stack_dev:
    name: Deploy Stack Dev
    needs: [vars]
    uses: ./.github/workflows/.deploy_stack.yml
    with:
      environment_name: dev
      command: apply
      tag: ${{ needs.vars.outputs.pr }}
      app_env: dev
    secrets: inherit
  e2e:
    name: E2E Tests
    needs: [deploy_stack_dev]
    uses: ./.github/workflows/.e2e.yml
    with:
      frontend_url: https://${{ needs.deploy_stack_dev.outputs.CF_DOMAIN }}
  deploy_stack_test:
    name: Deploy Stack Test
    needs: [vars, e2e]
    uses: ./.github/workflows/.deploy_stack.yml
    with:
      environment_name: dev # since we are using the same namespace env for dev and test
      command: apply
      tag: ${{ needs.vars.outputs.pr }}
      app_env: test
    secrets: inherit
