name: PR Close

on:
  pull_request:
    types: [closed]
concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write
jobs:
  cleanup-aws:
    name: Cleanup AWS
    uses: ./.github/workflows/.deployer.yml
    with:
      environment_name: dev
      command: destroy
    secrets: inherit