name: PR Close

on:
  pull_request:
    types: [closed]
concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write
jobs:
  cleanup-aws-database:
    name: Cleanup AWS Database
    uses: ./.github/workflows/.deployer.yml
    with:
      environment_name: dev
      command: destroy
      working_directory: database
      
    secrets: inherit
  cleanup-aws-api:
      name: Cleanup AWS API
      uses: ./.github/workflows/.deployer.yml
      with:
        environment_name: dev
        command: destroy
        working_directory: api
        app_env: ${{github.event.number}}
      secrets: inherit
  cleanup-aws-cf:
      name: Cleanup AWS CF
      uses: ./.github/workflows/.deployer.yml
      with:
        environment_name: dev
        command: destroy
        working_directory: frontend
        tag: ${{ github.event.number }}-${{ github.run_number }}
        app_env: ${{github.event.number}}
      secrets: inherit