name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write
env:
    AWS_REGION: ca-central-1
jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, migrations, frontend]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.3.0
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ github.event.number }}
          tags: ${{ github.event.number }}-${{ github.run_number }}
  tests-e2e:
    name: Tests
    needs: builds
    uses: ./.github/workflows/.tests.yml
    
  