name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write
jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, migrations]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.3.0
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ github.event.number }}
          tags: ${{ github.event.number }}-${{ github.run_number }}
  # https://github.com/bcgov/quickstart-openshift-helpers
  deploy-db:
    needs: [builds]
    name: Deploys Database
    uses: ./.github/workflows/.deployer.yml
    with:
      environment_name: dev
      command: apply
      working_directory: database
    secrets: inherit
  deploy-api:
    name: Deploys API
    needs: [deploy-db]
    uses: ./.github/workflows/.deployer.yml
    with:
      environment_name: dev
      command: apply
      working_directory: api
      tag: ${{ github.event.number }}-${{ github.run_number }}
      app_env: ${{github.event.number}}
    secrets: inherit
      

