name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  #builds:
  #  name: Builds
  #  runs-on: ubuntu-24.04
  ##  strategy:
  #    matrix:
  #      package: [backend, frontend, migrations]
  #  timeout-minutes: 10
  #  steps:
  #    - uses: bcgov-nr/action-builder-ghcr@v2.3.0
  #      with:
  #        keep_versions: 50
  #        package: ${{ matrix.package }}
  #        tag: ${{ github.event.number }}
  #        tag_fallback: latest
  #        triggers: ('${{ matrix.package }}/')

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    uses: ./.github/workflows/.deployer.yml
    with:
      environment_name: dev
    secrets: inherit
      

