name: Destroy Stack
on:
 workflow_dispatch:
  inputs:
    environment_name:
      description: 'The name of the environment to destroy resources from dev or test or prod(BE CAREFUL HERE)'
      required: true
      default: 'dev'
      type: string
    app_env:
      required: true
      type: string
      description: 'The APP env separates between AWS ENV and Actual APP, since AWS dev is where PR, and TEST is deployed'
<<<<<<< HEAD
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
=======
>>>>>>> a324caa80fb342404fe6ebe49d737c29a58e4c4d
jobs:
  cleanup-aws-database:
    name: Cleanup AWS Database
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment_name: ${{ github.event.inputs.environment_name }}
      command: destroy
      working_directory: database
<<<<<<< HEAD
      app_env: ${{ github.event.inputs.app_env }}
=======
      AWS_DEPLOY_ROLE_ARN: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
      AWS_LICENSE_PLATE: ${{ secrets.AWS_LICENSE_PLATE }}
>>>>>>> a324caa80fb342404fe6ebe49d737c29a58e4c4d
  cleanup-aws-api:
      name: Cleanup AWS API
      uses: ./.github/workflows/.deployer.yml
      secrets: inherit
      with:
        environment_name: ${{ github.event.inputs.environment_name }}
        command: destroy
        working_directory: api
        app_env: ${{ github.event.inputs.app_env }}
<<<<<<< HEAD
=======
        AWS_DEPLOY_ROLE_ARN: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
        AWS_LICENSE_PLATE: ${{ secrets.AWS_LICENSE_PLATE }}
>>>>>>> a324caa80fb342404fe6ebe49d737c29a58e4c4d
  cleanup-aws-cf:
      name: Cleanup AWS CF
      uses: ./.github/workflows/.deployer.yml
      secrets: inherit
      with:
        environment_name: ${{ github.event.inputs.environment_name }}
        command: destroy
        working_directory: frontend
        app_env: ${{ github.event.inputs.app_env }}
<<<<<<< HEAD
=======
        AWS_DEPLOY_ROLE_ARN: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
        AWS_LICENSE_PLATE: ${{ secrets.AWS_LICENSE_PLATE }}
>>>>>>> a324caa80fb342404fe6ebe49d737c29a58e4c4d
